mantis_uav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Velocity Controllers ---------------------------------------
  shoulder_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_shoulder
    pid: {p: 0.25, i: 0.2, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
  elbow_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_elbow
    pid: {p: 0.25, i: 0.2, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

  joint_position_controller:
    joint_shoulder:
      p: 2.5
      i: 0.0
      d: 0.0
      min: -1.6
      max: 1.6
    joint_elbow:
      p: 2.5
      i: 0.0
      d: 0.0
      min: -1.6
      max: 1.6
