#Parameter file for the Mantis MM-UAV Controller Aug node
controller_aug:
  # Path-following options
  contrail:
    fallback_to_pose: true
    autoswitch_tracking: true
    waypoint_hold_duration: 2.0
    waypoint_radius: 0.1
    waypoint_yaw_accuracy: 0.1

  control:
    pos:
      x:
        p: 8.0
        i: 2.0
        d: 0.0
        min: -2.0
        max: 2.0
      y:
        p: 8.0
        i: 2.0
        d: 0.0
        min: -2.0
        max: 2.0
      z:
        p: 7.5
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
    vel:
      x:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
      y:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
      z:
        p: 5.0
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
    ang:
      x:
        p: 6.5
        i: 0.0
        d: 0.0
        min: -1.57
        max: 1.57
      y:
        p: 6.5
        i: 0.0
        d: 0.0
        min: -1.57
        max: 1.57
      z:
        p: 2.8
        i: 0.0
        d: 0.0
        min: -0.75
        max: 0.75
    rate:
      x:
        p: 0.0433 #Slightly less than roll (cos(30)%) to even out motor thrust difference in the Hex
        i: 0.0
        d: 0.001
        min: -1.0
        max: 1.0
      y:
        p: 0.05
        i: 0.0
        d: 0.001
        min: -1.0
        max: 1.0
      z:
        p: 0.2
        i: 0.1
        d: 0.0
        min: -1.0
        max: 1.0
