#shoulder_controller:
#    controller:
#        package: dynamixel_controllers
#        module: joint_position_controller_dual_motor
#        type: JointPositionControllerDual
#    joint_name: shoulder_joint
#    joint_speed: 0.3
#    motor_master:
#        id: 1
#        init: 512
#        min: 200
#        max: 360
#    motor_slave:
#        id: 7

elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: elbow_joint
    joint_speed: 0.7
    motor:
        id: 1
        init: 0
        min: -512
        max: 512

