#Parameter file for the Mantis MM-UAV

controller_acro:
  rates:
    x:
      p: 0.05
      i: 0.01
      d: 0.001
      min: -0.5
      max: 0.5
    y:
      p: 0.05
      i: 0.01
      d: 0.001
      min: -0.5
      max: 0.5
    z:
      p: 0.2
      i: 0.1
      d: 0.0
      min: -0.2
      max: 0.2

motor:
  num: 4
  arm_len: 0.225 #m
  #thrust_max: 10.5225 # N
  kv: 920
  rpm_thrust_curve:
    m: 0.000797548 #0.0008318056
    c: -1.8044052
  drag_max: 1.2 # N

airframe: "quad_x4"

pwm:
  min: 1000
  max: 2000

body:
  num: 3
  b0:
    mass:
      m: 1.83497 # Base + props
      Ixx: 0.02961 # Maybe need to halve this
      Iyy: 0.02933 # Maybe need to halve this
      Izz: 0.05342 # Maybe need to halve this
      com: 0.0
    link:
      name: "mount"
      d: -0.05025
      t: 0.0
      r: 0.0
      a: 1.570796326794897
      type: "static"
  b1:
    mass:
      m: 0.10022841
      Ixx: 0.00001678
      Iyy: 0.00025428
      Izz: 0.00024944
      com: 0.15047991
    link:
      name: "joint_shoulder"
      d: 0.0
      t: -1.570796326794897
      r: 0.18325
      a: 0.0
      type: "twist_z"
      beta: 0.8
  b2:
    mass:
      m: 0.10022841
      Ixx: 0.00001678
      Iyy: 0.00025428
      Izz: 0.00024944
      com: 0.15047991
    link:
      name: "joint_elbow"
      d: 0.0
      t: 0.0
      r: 0.18325
      a: 0.0
      type: "twist_z"
      beta: 0.8
