#Parameter file for the Mantis MM-UAV Controller ID node

# Path-following options
contrail:
  fallback_to_pose: true
  waypoint_hold_duration: 1.0
  waypoint_radius: 0.2
  waypoint_yaw_accuracy: 0.1
  spline_res_per_sec: 5

control:
  pos:
    x:
      p: 3.0
      i: 0.0
      d: 0.0
      min: -2.0
      max: 2.0
    y:
      p: 3.0
      i: 0.0
      d: 0.0
      min: -2.0
      max: 2.0
    z:
      p: 3.0
      i: 0.0
      d: 0.0
      min: -5.0
      max: 5.0
  vel:
    x:
      p: 5.0
      i: 0.0
      d: 0.0
      min: -2.0
      max: 2.0
    y:
      p: 5.0
      i: 0.0
      d: 0.0
      min: -2.0
      max: 2.0
    z:
      p: 5.0
      i: 0.0
      d: 0.0
      min: -5.0
      max: 5.0
  ang:
    x:
      p: 3.0
      i: 0.0
      d: 0.0
      min: -1.57
      max: 1.57
    y:
      p: 3.0
      i: 0.0
      d: 0.0
      min: -1.57
      max: 1.57
    z:
      p: 3.0
      i: 0.0
      d: 0.0
      min: -0.75
      max: 0.75
  rate:
    x:
      p: 15.0
      i: 0.0
      d: 0.0
      min: -15.0
      max: 15.0
    y:
      p: 15.0
      i: 0.0
      d: 0.0
      min: -15.0
      max: 15.0
    z:
      p: 15.0
      i: 0.0
      d: 0.0
      min: -5.0
      max: 5.0
