#Parameter file for the Mantis MM-UAV

motor:
  num: 6
  arm_len: 0.275 #m
  #thrust_max: 10.5225 # N
  kv: 920
  rpm_thrust_curve:
    m: 0.000797548 #0.0008318056
    c: -1.8044052
  drag_max: 1.2 # N

pwm:
  min: 1000
  max: 2000

takeoff:
  x: 0.0
  y: 0.0
  z: 2.0

controller_aug:
  control:
    pos:
      x:
        p: 4.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
        tau: 0.02
      y:
        p: 4.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
        tau: 0.02
      z:
        p: 7.5
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
        tau: 0.02
    vel:
      x:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
        tau: 0.02
      y:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
        tau: 0.02
      z:
        p: 5.0
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
        tau: 0.02
    ang:
      x:
        p: 6.5
        i: 0.0
        d: 0.0
        min: -1.57
        max: 1.57
        tau: 0.02
      y:
        p: 6.5
        i: 0.0
        d: 0.0
        min: -1.57
        max: 1.57
        tau: 0.02
      z:
        p: 2.8
        i: 0.0
        d: 0.0
        min: -0.75
        max: 0.75
        tau: 0.02
    rate:
      x:
        p: 0.05
        i: 0.0
        d: 0.005
        min: -1.0
        max: 1.0
        tau: 0.02
      y:
        p: 0.05
        i: 0.0
        d: 0.005
        min: -1.0
        max: 1.0
        tau: 0.02
      z:
        p: 0.2
        i: 0.1
        d: 0.0
        min: -1.0
        max: 1.0
        tau: 0.02

body:
  num: 3
  b0:
    mass:
      m: 1.83497 # Base + props
      Ix: 0.02961 # Maybe need to halve this
      Iy: 0.02933 # Maybe need to halve this
      Iz: 0.05342 # Maybe need to halve this
    com: 0.0
    link:
      name: "mount"
      d: -0.05025
      t: 0.0
      r: 0.0
      a: 1.570796326794897
      type: "static"
  b1:
    mass:
      m: 0.10022841
      Ix: 0.00001678
      Iy: 0.00025428
      Iz: 0.00024944
    com: 0.15047991
    link:
      name: "joint_shoulder"
      d: 0.0
      t: -1.570796326794897
      r: 0.18325
      a: 0.0
      type: "twist_z"
      beta: 0.8
  b2:
    mass:
      m: 0.10022841
      Ix: 0.00001678
      Iy: 0.00025428
      Iz: 0.00024944
    com: 0.15047991
    link:
      name: "joint_elbow"
      d: 0.0
      t: 0.0
      r: 0.18325
      a: 0.0
      type: "twist_z"
      beta: 0.8
