control:
  ang:
    p: 4.5
    yaw_w: 0.6
  rate:
    x:
      p: 10.0
      i: 0.0
      d: 0.0
      min: -20.0
      max: 20.0
    y:
      p: 10.0
      i: 0.0
      d: 0.0
      min: -20.0
      max: 20.0
    z:
      p: 10.0
      i: 0.0
      d: 0.0
      min: -20.0
      max: 20.0
