#Parameter file for the Mantis MM-UAV Controller ID node

controller_id:
  control:
    pos:
      x:
        p: 8.0
        i: 2.0
        d: 0.0
        min: -2.0
        max: 2.0
      y:
        p: 8.0
        i: 2.0
        d: 0.0
        min: -2.0
        max: 2.0
      z:
        p: 7.5
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
    vel:
      x:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
      y:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
      z:
        p: 5.0
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
    ang:
      x:
        p: 3.0
        i: 0.0
        d: 0.0
        min: -1.57
        max: 1.57
      y:
        p: 3.0
        i: 0.0
        d: 0.0
        min: -1.57
        max: 1.57
      z:
        p: 1.5
        i: 0.0
        d: 0.0
        min: -0.75
        max: 0.75
    rate:
      x:
        p: 10.0
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
      y:
        p: 10.0
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
      z:
        p: 10.0
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
