#Parameter file for the Mantis MM-UAV Controller ID node

controller_id:
  gain:
    pos:
      xy:
        p: 4.0
        i: 0.0
      z:
        p: 7.5
        i: 0.0
    vel:
      xy:
        p: 2.0
      z:
        p: 5.0
    rot:
      ang:
        p: 3.0
      rate:
        p: 10.0
