#Parameter file for the Mantis MM-UAV
takeoff:
  x: 0.0
  y: 0.0
  z: 1.0

controller_aug:
  control:
    pos:
      x:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
        tau: 0.02
      y:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
        tau: 0.02
      z:
        p: 4.0
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
        tau: 0.02
    vel:
      x:
        p: 1.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
        tau: 0.02
      y:
        p: 1.0
        i: 0.0
        d: 0.0
        min: -2.0
        max: 2.0
        tau: 0.02
      z:
        p: 2.0
        i: 0.0
        d: 0.0
        min: -5.0
        max: 5.0
        tau: 0.02
    ang:
      x:
        p: 6.5
        i: 0.0
        d: 0.0
        min: -1.57
        max: 1.57
        tau: 0.02
      y:
        p: 6.5
        i: 0.0
        d: 0.0
        min: -1.57
        max: 1.57
        tau: 0.02
      z:
        p: 2.8
        i: 0.0
        d: 0.0
        min: -0.75
        max: 0.75
        tau: 0.02
    rate:
      x:
        p: 0.0433 #Slightly less than roll (cos(30)%) to even out motor thrust difference in the Hex
        i: 0.0
        d: 0.005
        min: -1.0
        max: 1.0
        tau: 0.02
      y:
        p: 0.05
        i: 0.0
        d: 0.005
        min: -1.0
        max: 1.0
        tau: 0.02
      z:
        p: 0.2
        i: 0.1
        d: 0.0
        min: -1.0
        max: 1.0
        tau: 0.02
