# Common configuration for the mavel velocity controller

# Control
control_rate: 50.0
control_frame: "map"

throttle:
  min: 0.0
  mid: 0.2
  max: 0.9

# Maximum roll/pitch in radians
tilt_max: 0.39

# Emergency Landing Velocity (must be negative!)
failsafe_land_vel: -0.2

# Data Stream
min_rate:
  state:
    state: 0.2
    odometry: 10.0
  reference:
    trajectory: 10.0
    position: 5.0
    velocity: 10.0
    acceleration: 30.0

# PID Controllers
control:
  pos:
    x:
      p: 1.25
      i: 0.0
      d: 0.1
      min: -2.0
      max: 2.0
    y:
      p: 1.25
      i: 0.0
      d: 0.1
      min: -2.0
      max: 2.0
    z:
      p: 1.0
      i: 0.0
      d: 0.0
      min: -1.0
      max: 2.0
  vel:
    x:
      p: 0.09
      i: 0.00
      d: 0.01
      min: -0.2
      max: 0.2
    y:
      p: 0.09
      i: 0.00
      d: 0.01
      min: -0.2
      max: 0.2
    z:
      p: 0.1
      i: 0.02
      d: 0.0
      min: -0.5
      max: 0.5

