mantis_uav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  shoulder_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_shoulder
    pid: {p: 0.25, i: 0.0, d: 0.0}
  elbow_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_elbow
    pid: {p: 0.25, i: 0.0, d: 0.0}


  #joint_position_controller:
  #  type: "effort_controllers/JointGroupVeclocityController"
  #  joints:
  #    - joint_shoulder
  #    - joint_elbow
  #  joint_shoulder:
  #    pid: {p: 0.25, i: 0.1, d: 0.0}
  #  joint_elbow:
  #    pid: {p: 0.25, i: 0.1, d: 0.0}
