mantis_uav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Velocity Controllers ---------------------------------------
  shoulder_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_shoulder
    pid: {p: 0.25, i: 0.2, d: 0.0}
  elbow_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_elbow
    pid: {p: 0.25, i: 0.2, d: 0.0}

  joint_position_controller:
    joint_shoulder:
      command: shoulder_velocity_controller
      pid: {p: 1.25, i: 0.0, d: 0.0}
      limits: {min: -0.5, max: 0.5}
    joint_elbow:
      command: elbow_velocity_controller
      pid: {p: 1.25, i: 0.0, d: 0.0}
      limits: {min: -0.5, max: 0.5}
