# Common configuration for servo controller PIDs

# Data Stream
joint:
  shoulder:
    pos:
      ff: 1.0
    vel:
      kp: 0.6
      ki: 0.1
      kd: 0.0
      tau: 0.02
      max: 1.0
    eff:
      max: 2.0
  elbow:
    pos:
      ff: 0.5
    vel:
      kp: 0.4
      ki: 0.1
      kd: 0.0
      tau: 0.02
      max: 1.0
    eff:
      max: 2.0
